library(igraph)
newa<- read.csv("SmallWorldGraphMatrix.csv", header = FALSE,sep = ",")
 ajau<-graph.adjacency(newa,mode="undirected")
names<- get.vertex.attribute(ajau, "name")
#ajau<-graph.data.frame(aja,directed=FALSE)
#names<- get.vertex.attribute(ajau, "name")
pt<-c(10,46,66)
V(ajau)[pt]$color<-"Green"
#E(ajau)$color<-rainbow(15)
plot(ajau,vertex.size=3,vertex.label.dist=0.3,vertex.label=names,edge.color=rainbow(200))
